// <auto-generated />
using System;
using Ecommerce.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ecommerce.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("28ec15db-cf38-47e9-b228-7fc5fad3dbff"),
                            Name = "Product X",
                            Price = 9.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = new Guid("7b99905c-24b1-45a3-b453-30316effa3d4"),
                            Name = "Product Y",
                            Price = 19.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("1433c03b-2e97-4535-962f-31c4b89e875a"),
                            Name = "Product Z",
                            Price = 29.99m,
                            Stock = 25
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
